# Generated by Django 4.1.2 on 2022-10-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='descriptin',
            new_name='description',
        ),
    ]
