from rest_framework import serializers
from .models import Meal, Rating
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token

# Serializers to meals and rating


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('id', 'username', 'password')
        extra_kwargs = {'password': {'write_only' : True, 'required' : True}} # Important Line

    # user creation with token autogenerated
    # def create(self, validated_data):
    #         user  = User.objects.create_user(**validated_data)
    #         Token.objects.create(user=user )
    #         return user

class MealSerializer(serializers.ModelSerializer):
    class Meta:
        model = Meal
        fields = ('id', 'title', 'description', 'noOfRatings', 'avgRatings')


class RatingSerializer(serializers.ModelSerializer):
    class Meta:
        model = Rating
        fields = ('id', 'stars', 'user', 'meal')


